### ISSUE TITLE
Allow null values in EntryStream.toCustomMap

### ISSUE THREAD

**Issue by piotrturski** [amaembo/streamex#148]
`EntryStream.toMapConsumer` uses `Objects.requireNonNull(entry.getValue()))`. why you prevent nulls? null is a valid value and maps can distinguish between `null` and 'no value'. But `EntryStream.toCustomMap` implementation effectively prevents creating map with null values

**Comment by amaembo** [comment]
To be consistent with Collectors.toMap() and with concurrent maps.

**Comment by piotrturski** [comment]
`Collectors.toMap(..., Supplier<M> mapSupplier)` doesn't prevent null values

**Comment by amaembo** [comment]
Have you tried? I did:

```java
import java.util.*;
import java.util.stream.*;

public class Test {
  public static void main(String[] args) {
    Stream.of("a", "b", "c").collect(
           Collectors.toMap(x -> x, x -> null, (a, b) -> a, HashMap::new));
  }
}
```

Output:

```
Exception in thread "main" java.lang.NullPointerException
        at java.util.HashMap.merge(Unknown Source)
        at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
        at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at Test.main(Test.java:6)
```

**Comment by donmutti** [comment]
https://bugs.openjdk.java.net/browse/JDK-8148463
