### ISSUE TITLE
Should StreamEx work in Android N?

### ISSUE THREAD

**Issue by dsaff** [amaembo/streamex#150]
I'm just starting to debug, but I tried to build an Android app using StreamEx, and it's failing to run, giving this error:

java.lang.VerifyError: Rejecting class one.util.streamex.StreamEx that attempts to sub-type erroneous class one.util.streamex.AbstractStreamEx (declaration of 'one.util.streamex.StreamEx' appears in /data/app/net.saff.jiminy-2/base.apk)
                                                                     at one.util.streamex.StreamEx.of(StreamEx.java:2036)
                                                                     at net.saff.jiminy.core.home.HomeScreen.getFields(HomeScreen.java:65)
                                                                     at net.saff.jiminy.core.screen.StackScreen.show(StackScreen.java:16)
                                                                     at net.saff.jiminy.core.screen.AbstractScreenStack.show(AbstractScreenStack.java:41)
                                                                     at net.saff.jiminy.core.ScreenStackImpl.refresh(ScreenStackImpl.java:15)
                                                                     at net.saff.jiminy.core.screen.AbstractScreenStack.push(AbstractScreenStack.java:13)
                                                                     at net.saff.jiminy.core.MainActivityController.onCreate(MainActivityController.java:56)
                                                                     at net.saff.jiminy.MainActivity.onCreate(MainActivity.java:69)
                                                                     at android.app.Activity.performCreate(Activity.java:6679)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                  Caused by: java.lang.VerifyError: Verifier rejected class one.util.streamex.AbstractStreamEx: one.util.streamex.AbstractStreamEx one.util.streamex.AbstractStreamEx.callWhile(java.util.function.Predicate, int): [0xFFFFFFFF] unexpected opcode unused-fa (declaration of 'one.util.streamex.AbstractStreamEx' appears in /data/app/net.saff.jiminy-2/base.apk)
                                                                     at one.util.streamex.StreamEx.of(StreamEx.java:2036) 
                                                                     at net.saff.jiminy.core.home.HomeScreen.getFields(HomeScreen.java:65) 
                                                                     at net.saff.jiminy.core.screen.StackScreen.show(StackScreen.java:16) 
                                                                     at net.saff.jiminy.core.screen.AbstractScreenStack.show(AbstractScreenStack.java:41) 
                                                                     at net.saff.jiminy.core.ScreenStackImpl.refresh(ScreenStackImpl.java:15) 
                                                                     at net.saff.jiminy.core.screen.AbstractScreenStack.push(AbstractScreenStack.java:13) 
                                                                     at net.saff.jiminy.core.MainActivityController.onCreate(MainActivityController.java:56) 
                                                                     at net.saff.jiminy.MainActivity.onCreate(MainActivity.java:69) 
                                                                     at android.app.Activity.performCreate(Activity.java:6679) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 

I'll continue to debug, but is this a known issue with Android?  This is my first attempt to build an Android app using any Java 8 APIs

**Comment by amaembo** [comment]
Hello! `AbstractStreamEx.callWhile` uses `MethodHandle.invokeExact` method which is a signature polymorphic method (see JVM Specification, [https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-2.html#jvms-2.9 §2.9]). It's likely that Android VM does not follow the JVM specification, so it does not support signature polymorphic method.

In general I plan to get rid of this invokeExact call in my attempt to convert StreamEx to multi-release JAR (see [http://openjdk.java.net/jeps/238 JEP 238]) in future.

**Comment by amaembo** [comment]
All methodhandle-related stuff is moved away to the separate class which is not loaded before Java 9, so modern StreamEx versions should work with Android. Please reopen if you still have issues.
