### ISSUE TITLE
IllegalStateException on toList() call in parallel stream

### ISSUE THREAD

**Issue by KTannenberg** [amaembo/streamex#184]
There seems to be a problem with `toList()` method available in for StreamEx streams when they are executed in parallel, `collect(Collectors.toList())` works as expected at the same time.

Environment: Java 8u171, StreamEx 0.6.7, JUnit 4.12
Test case: https://gist.github.com/KTannenberg/62817706c05037cc43f87f5bba1a6bea

Stack trace:
```
java.lang.IllegalStateException: size passed to Sink.begin exceeds array length
	at java.util.stream.Nodes$SizedCollectorTask.begin(Nodes.java:1887)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:480)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.Nodes$SizedCollectorTask.compute(Nodes.java:1878)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.Nodes.collect(Nodes.java:325)
	at java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:109)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:540)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:344)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1154)
	at gist.stream.StreamExToListTest.testStreamExFailing(StreamExToListTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by KTannenberg** [comment]
It looks like problem occurs when original spliterator is about to be consumed after several splits. Updated test (https://gist.github.com/KTannenberg/d04c3cb266b2f52238e28d1c46bd357d) produces following output before failing with same stacktrace:

```
>> using collect(Collectors.toList())
split #0
split #0
advance #2
consume #2 = 4
advance #2
advance #0
consume #0 = 5
consume #0 = 6
advance #0
split #1
advance #1
consume #1 = 2
consume #1 = 3
advance #1
advance #3
consume #3 = 1
advance #3

>> using toList()
split #0
split #0
advance #2
consume #2 = 4
advance #2
split #1
advance #1
consume #1 = 2
consume #1 = 3
advance #1
advance #3
consume #3 = 1
advance #3
```

According to this offspring spliterators `#1`, `#2` and `#3` are consumed fine, exception is produced before call to `tryAdvance()` on spliterator `#0`, maybe too small array is allocated for results in `AbstractStreamEx.toArray`?

**Comment by amaembo** [comment]
Very interesting. Does the problem exist as well if you replace `toList()` with `toArray()`? Does the problem appear only when custom pool is used?

**Comment by amaembo** [comment]
Your Spliterator violates the contract. Its `characteristics()` method returns base spliterator characteristics which could be `SIZED | SUBSIZED`. However your spliterator fails to provide exact size in the `estimateSize()` method after splitting. If you cannot provide exact size of every chunk, you should return `base.characteristics() & ~(SIZED | SUBSIZED)` or something like this. The `collect(toList())` implementation is less optimal and it does not use these characteristics while `toList()` may optimize the List creation if these characteristics are specified. However if you specify them, you must return exact size from `estimateSize()` method.

**Comment by KTannenberg** [comment]
Result of first call to `estimateSize()` is used to determine size of allocated array? Then it seems to be the case, because initially it will be 3 in this test case, but further splits results in more chunks.

**Comment by amaembo** [comment]
I did not run your code, but if you're able to report exact initial size, then yes, you can keep the SIZED characteristic. This may help to optimize in sequential case.
