### ISSUE TITLE
Change default implementation of EntryStream#sorted

### ISSUE THREAD

**Issue by SimSonic** [amaembo/streamex#207]
### Problem
When calling .sorted() on any EntryStream it fails with ClassCastException.

### Example
```java
public static void main(String[] args) {
    String result = StreamEx.of("3", "1", "4", "2")
            .mapToEntry(Function.identity())
            .sorted()
            .values()
            .joining();

    System.out.println(result);
}
```
Output:
```
Exception in thread "main" java.lang.ClassCastException: class java.util.AbstractMap$SimpleImmutableEntry cannot be cast to class java.lang.Comparable (java.util.AbstractMap$SimpleImmutableEntry and java.lang.Comparable are in module java.base of loader 'bootstrap')
	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1516)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:68)
	at one.util.streamex.StreamEx.joining(StreamEx.java:748)
...
```
### Solution 1
Make default behavior of `.sorted()` identical to `.sorted(Map.Entry.comparingByKey())`.

OR

### Solution 2
Add two new methods to EntryStream: `.sortedByKeys()` and `.sortedByValues()`.

Thanks :)

**Comment by amaembo** [comment]
As `EntryStream` implements the `Stream<Entry>` interface, it must follow the interface specification, so we cannot change the semantics of the standard method, which is specified to sort using natural order. I thought about adding `.sortedByKey()` and `.sortedByValue()`, but it's not much shorter than `.sortedBy(Entry::getKey)` and `.sortedBy(Entry::getValue)`. Though I can still consider adding them.

**Comment by SimSonic** [comment]
I understand.

Hovewer, can it be good idea to write these thoughts into javadocs of `.sorted()` and, optionally, mark it deprecated?

**Comment by amaembo** [comment]
Javadoc update is possible, yes. Deprecation doesn't sound right for me. I know that Guava abuses `@Deprecated` annotation to mark unsupported methods, but this doesn't seem right to me. And this is not quite unsupported. You may create an EntryStream over a custom Map whose entries are Comparable, and in this case it should work.

**Comment by SimSonic** [comment]
Thanks!

**Comment by amaembo** [comment]
A type-safe possibility is to add `.sortedByKey(Comparator)` and `.sortedByValue(Comparator)`, so you can use `.sortedByKey(naturalOrder())`. However this is even longer than existing alternatives.
